# Generated by Django 6.0.5 on 2026-05-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_alter_category_options_alter_profile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasecheck",
            name="worthit_score",
            field=models.PositiveIntegerField(default=50),
        ),
    ]
